apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
    app.kubernetes.io/instance: wordpress
    env: test
    type: frontend
  name: wordpress
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: 'wordpress:latest'
          name: wordpress
