apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    app.kubernetes.io/instance: wordpress
    env: test
    type: frontend
  name: wordpress
  namespace: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: NodePort