apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    env: test
    app: wordpress
    type: frontend
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
