apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shortner
    app.kubernetes.io/instance: url-shortner-1
    env: test
    type: restapi
  name: url-shortner
  namespace: myapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: url-shortner
  type: NodePort