apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shortener
    app.kubernetes.io/instance: url-shortener-1
    env: test
    type: restapi
  name: url-shortener
  namespace: myapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: url-shortener
  type: NodePort