apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shortner
    app.kubernetes.io/instance: myapp1
    env: test
    type: restapi
  name: url-shortner
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortner
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
        - image: 'sainadh086/url-shortner:latest'
          name: url-shortner
